### ISSUE TITLE
Silent Mode

### ISSUE THREAD

**Issue by stefan-niedermann** [samaxes/minify-maven-plugin#100]
I have a large Javascript-Project. If i use the Plugin i get
```
[INFO] Processing source file [file.js].
```
50-60 times what spams my maven output.

As a user i'd like to have an option to set the plugin silent except an exception occurs or something went wrong.

**Comment by samaxes** [comment]
Running maven with the `-q` or `--quiet` parameter only shows errors.
Unfortunately there isn't an option that also shows warnings, but no info level.
