### ISSUE TITLE
Closure compiler creates a map that points to a *.tmp file

### ISSUE THREAD

**Issue by nurv** [samaxes/minify-maven-plugin#103]
The plugin currently has a concatenation step before sending the file into the magnification. 

This behaviour is at odds with the Closure Compiler. The compiler expects to receive all the files separately, one to make sense of @private annotations and also for the the .map file. 

If you compile with the latest version of the plugin, the final .map file will point to a transient file called <outputfile>.tmp that does not exist on the final output.

For an example of the configuration you can see this file: 
* https://github.com/nurv/bennu/blob/feature/closureHints/bennu-toolkit/pom.xml

**Comment by i045053** [comment]
Is that what you are looking for?  https://github.com/samaxes/minify-maven-plugin/issues/98

**Comment by nurv** [comment]
@i045053 you've submited an Issue and not a Pull Request. You should submit a pull request if you wish for me to view the code.

**Comment by i045053** [comment]
Sorry, new to github, the pull request is here:  https://github.com/samaxes/minify-maven-plugin/pull/97

**Comment by samaxes** [comment]
I will come back to this issue on the next release.
