### ISSUE TITLE
Minification with suffix adds extra point (.) to output file

### ISSUE THREAD

**Issue by Valijon** [samaxes/minify-maven-plugin#104]
Different output generated with version 1.5.2 and 1.7.4.
Expected **main-1.0.js**, but generated **main.-1.0.js** (for version 1.7.4)
Plugin configuration

	<plugin>
		<groupId>com.samaxes.maven</groupId>
		<artifactId>minify-maven-plugin</artifactId>
		<version>1.5.2</version>
		<executions>
			<execution>
				<id>default-minify</id>
				<phase>process-resources</phase>
				<configuration>
					<webappSourceDir>${basedir}/src/main/webapp</webappSourceDir>

					<jsSourceDir>resources/js</jsSourceDir>
					<jsTargetDir>resources/js</jsTargetDir>
					<jsSourceIncludes>
						<jsSourceInclude>*.js</jsSourceInclude>
					</jsSourceIncludes>
					<suffix>-${project.version}</suffix>
					<skipMerge>true</skipMerge>
				</configuration>
				<goals>
					<goal>minify</goal>
				</goals>
			</execution>
		</executions>
	</plugin>

**Comment by sergeypalyanov** [comment]
This also happens with no suffix specified.
If the final file name is **style.css**, the minified file name becomes **style..min.css**.
And what's strange, it doesn't happen when I build project under the Windows. But it happens on Linux machine.

**Comment by jieryn** [comment]
This error doesn't occur on recent versions of the plugin, please close the issue.

**Comment by samaxes** [comment]
Fixed in version 1.7.5.
