### ISSUE TITLE
Setup on Eclipse + Tomcat environment

### ISSUE THREAD

**Issue by bjadel** [samaxes/minify-maven-plugin#106]
Hi,

my problem is to find a right setup for my tomcat and eclipse environment. Currently I use two sections in my pom.xml. The first one is the plugin:
```xml
<plugin>
   <groupId>com.samaxes.maven</groupId>
	<artifactId>minify-maven-plugin</artifactId>
	<version>1.7.4</version>
	<executions>
		<execution>
		    <id>default-minify</id>
		     <configuration>
		     <cssSourceFiles></cssSourceFiles>
		     <jsSourceDir>static/js/app</jsSourceDir>
		     <jsSourceFiles>
		     	<jsSourceFile>file.js</jsSourceFile>
		     </jsSourceFiles>
		     <webappTargetDir>${basedir}/src/main/webapp</webappTargetDir>
		     <jsEngine>CLOSURE</jsEngine>
		     </configuration>
		     <goals>
		        <goal>minify</goal>
		     </goals>
		  </execution>
	</executions>
</plugin>
```

The second one is a part of m2e plugin configuration in my pom.xml:
```xml
<plugin>
	<groupId>org.eclipse.m2e</groupId>
	<artifactId>lifecycle-mapping</artifactId>
		[...]
		<pluginExecution>
			<pluginExecutionFilter>
				<groupId>com.samaxes.maven</groupId>
				<artifactId>minify-maven-plugin</artifactId>
				<versionRange>[1.0.0,)</versionRange>
				<goals>
					<goal>minify</goal>
				</goals>
			</pluginExecutionFilter>
			<action>
				<execute>
					<runOnIncremental>true</runOnIncremental>
				</execute>
			</action>
		</pluginExecution>
		[...]
```

The problem is a never ending build cycle and creation of files in /tmp like 'script.min.js2342342342254.gz' during the tomcat is running. After one minute are creates 60 files.

How can I solve this problem?

Thanks in advance
Regards Björn

**Comment by agabrys** [comment]
You configured loop.

1. Plugin saves generated files in sources directory.
2. Eclipse executes plugin after any changes in sources. Jump to 1.

You should save generated files in target directory instead of sources directory.

**Comment by samaxes** [comment]
Thanks @agabrys for spotting that.
I'm now closing this issue.
