### ISSUE TITLE
Javascript Getter and Setter function

### ISSUE THREAD

**Issue by pratickchokhani** [samaxes/minify-maven-plugin#111]
I was integrating this with my project. There is one issue, the project is using YUI Compressor Version: 2.4.7 which contains a bug.

In this the javascript getter and setter function is not minified properly.

Eg: 
get date () {
    return this.currentDate
},

is minified to:

get datefunction(){return this.currentDate}

This bug is fixed in YUI Compressor Version: 2.4.8. 

Can the compressor version be upgraded?

**Comment by samaxes** [comment]
Next version of the plugin has been updated to YUI Compressor 2.4.8.

**Comment by pratickchokhani** [comment]
Thank you. I will be very helpful for our project.
