### ISSUE TITLE
Updated release of minify-maven-plugin with latest closure-compiler

### ISSUE THREAD

**Issue by andreasrosdal** [samaxes/minify-maven-plugin#112]
Hi, I would really like a new release of minify-maven-plugin with the latest version of Google Closure-compiler included. The latest version of closure-compiler is v20151216 and can be found here: https://github.com/google/closure-compiler/releases

It seems the latest version of minify-maven-plugin was released 26 Aug 2014.
How can I use it with the latest version of Closure-compiler?

**Comment by samaxes** [comment]
Hi @andreasrosdal, starting with Maven 2.0.9 it's possible to override plugin's dependencies.
Take a look at [How to override a plugin's dependency in Maven](http://blog.sonatype.com/2008/04/how-to-override-a-plugins-dependency-in-maven/).
