### ISSUE TITLE
closure compiler is talking to much

### ISSUE THREAD

**Issue by otti88** [samaxes/minify-maven-plugin#124]
Hey,
i like your work very much and appreciate to use it. It works fine and does an awesome job. The only thing anoying me is, it gives a lot of output in the console. And this makes the compiling process to a hole coffee brake. 
I got a lot of warnings about extern libraries, which i won't change. It is working with the warnings pretty good. So maybe you can add the option for the warning level set to QUIET ? i know there is a flag on closure compiler api to set the warning_level to quiet. so may you could add this option for maven too? It would speed up the compiling process enormously. Would love that.

Thanks
Otti

**Comment by samaxes** [comment]
In the next version of the plugin - 1.7.5, there is an option to define [Closure Compiler warning levels](https://github.com/google/closure-compiler/wiki/Warnings).
