### ISSUE TITLE
Minification fails if the JS contains a call to Promise.prototype.catch()

### ISSUE THREAD

**Issue by polentino** [samaxes/minify-maven-plugin#126]
Looks like the minifier doesn't like the method name '_catch()_', because it conflicts with the JS keyword _catch_.

Therefore, any JS file that's using the [Promise object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch), and especially its [Promise.prototype.catch(onRejected)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch) method to handle exception, will cause the minification process to fail.

Since your plugin, according to the docs, it's using YUI compressor under the hood, and [they had the very same issue as well](https://github.com/yui/yuicompressor/issues/203), which is now fixed, it should be trivial for you to provide a fix.

Thanks :)

**Comment by nvurgaft** [comment]
Yes, YUI should be updated, it fails on ES6 lambdas and these have been around for a while. Have you tested with the Closure compressor ?

**Comment by polentino** [comment]
@nvurgaft nope, at work we're just using that one.

**Comment by samaxes** [comment]
This should be fixed in the next version (1.7.5).
Both YUI Compressor and Closure Compiler have updated to the last version.
