### ISSUE TITLE
Closure parameter to @define JS variables

### ISSUE THREAD

**Issue by OzoneGrif** [samaxes/minify-maven-plugin#127]
I have a simple code to add DEBUG informations during development.
```
/**
 * For the Closure compiler
 * @define {boolean}
 */
var DEBUG = true;
[...]
DEBUG && log(stuff);
```
The Closure compiler's documentation states that you can force a variable with the parameter :
`--define='DEBUG=false'`

I don't see a way to inject this parameter with samaxes. Is it possible?

**Comment by samaxes** [comment]
Just added support for this in version 1.7.5.
