### ISSUE TITLE
ES6 support

### ISSUE THREAD

**Issue by metame** [samaxes/minify-maven-plugin#128]
Since the Closure compiler allows ES6 as a language, how do I specify this in my configuration and have it transpiled to ES5?  This isn't covered in any documentation.

**Comment by dotmartin** [comment]
Is it possible to let it pass through as ES6 today? We use shims to add support for ES6 but the fat arrow notation halts the minification and logs a syntax error.

**Comment by samaxes** [comment]
ES6 is supported (and the default language) in the last version 1.7.5 (not yet released though).

**Comment by janpetryk** [comment]
How do I enable ES6 in the configuration? I can't find it in documentation.

**Comment by kmh0237** [comment]
@samaxes @janpetryk and anyone else confused about this, you need to set jsEngine to CLOSURE (see http://samaxes.github.io/minify-maven-plugin/minify-mojo.html) to be able to use es6.  Maybe this should be the default?  es5 is pretty outdated at this point and the current default YUI is not being updated.
