### ISSUE TITLE
<skipMerge>true</skipMerge> overwrites same file multiple times

### ISSUE THREAD

**Issue by bjornbak** [samaxes/minify-maven-plugin#130]
minify-maven-plugin default merges all css / js into one file.

I need to have a list of files minified individually.

When I add <skipMerge>true</skipMerge> I would expect to end up with a minified file per source file.

But each individual minification is saved to script.min.js or style.min.js which is overwritten for each source file.

I would expect that source1.js and source2.js would be minified to source1.min.js and source2.min.js

**Comment by Selaron** [comment]
I can confirm this. Seemes it was introduces with version 1.7.5 of the plugin.
A workaround that worked for me is to downgrade to <version>1.7.4</version>.

**Comment by samaxes** [comment]
Sorry guys.
Fixed in version 1.7.6.
