### ISSUE TITLE
nosuffix true doesn't overwrite source files

### ISSUE THREAD

**Issue by rohifa** [samaxes/minify-maven-plugin#50]
Hi, 
I'd like to overwrite on build time the original js and css files with the minified versions, keeping the same file name. I added <nosuffix>true</nosuffix> to the exection configuration, but it actually doesn't work. Other parameters works (like skipMerge) but not this one.
p.s.: I also opened a question on stackoverflow but I report here as well
http://stackoverflow.com/questions/22117824/using-samaxes-minify-nosuffix-to-overwrite-original-files

**Comment by nestdimon** [comment]
Yeah, it doesn't work even in 1.7.4. In ```target``` folder minified file is overridden as supposed, but in produced ```war``` file is not. ```<phase>``` specified as ```package```.

**Comment by yuridolzhenko** [comment]
Yep, same thing when packaging stuff into war. Anybody has found a solution/workaround?

**Comment by yuridolzhenko** [comment]
Actually executing it in compile phase did the trick for me in case of war packaging.

**Comment by khelu** [comment]
@timothystone , @nestdimon :
I had the same problem, but keep in mind that 'maven-war-plugin' is overriding in the end the original source files over the new minified ones.
So, if you want to keep 
`<configuration>
		<nosuffix>true</nosuffix>
		<skipMerge>true</skipMerge>
                ...
</configuration>` 
, you should stick to the `<phase>package</phase>` and also equally important, you should exclude your original css and js files from war like this:
`<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<version>2.2</version>
				<configuration>
					...
					<warSourceExcludes>**/file-1.js,**/file-2.js,**/file1.css</warSourceExcludes>
				</configuration>
			</plugin>`

After that, your war file will have only the minified files in it.

Hope it helps, it did for me.

**Comment by nhducseuit** [comment]
@khelu  doesn't fix for me. After configuring the `warSourceExcludes` the war file is produced without js files.

**Comment by nhducseuit** [comment]
I follow the solution here https://stackoverflow.com/a/13236382/7750784
In that, I need to remove `<phase>package</phase>`  when run minify goal so that it runs with default phase.
