### ISSUE TITLE
Add option to turn of sorting included files alphabetically by file name before merging

### ISSUE THREAD

**Issue by dblazeka** [samaxes/minify-maven-plugin#56]
It would be great if such option existed because JS ordering is pretty importans in some cases so if there were an option like <sortAlpha>false</sortAlpha> in configuration plugin would merge file in the same order as jsSourceIncludes are listed in pom. Thank you.

**Comment by NatiiDC** [comment]
If change ´jsSourceIncludes´ by ´jsSourceFiles´, isn't run minify. 

`[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!`
