### ISSUE TITLE
Option to not include the source location comment

### ISSUE THREAD

**Issue by sgoo** [samaxes/minify-maven-plugin#65]
Would it be possible to include an option to allow source map generation but not add the comment to the end of the minified JS.
This would allow for people who want to use the HTTP header to send the source map location, or possibly conditionally include the comment or header.

Thanks, Scott.

**Comment by samaxes** [comment]
Hi @sgoo, I apologize for taking so long to come back at you.
I'm closing the issue for now.
However, if you strongly believe it will be of great benefit to the plugin, feel free to reopen it.
