### ISSUE TITLE
GAE somefiles are not pushing to the repo

### ISSUE THREAD

**Issue by caztial** [samaxes/minify-maven-plugin#76]
Local jetty server works fine but when I tried to push to Google app engine with mvn appengine:update some of the minified files are not uploading along with an image file.. I removed the plugin and pused again then it all worked fine

**Comment by samaxes** [comment]
Hi @caztial, have you had the time to digg into this issue, or can I close the issue?

**Comment by caztial** [comment]
nope I didn't get any time to digg into this.. you can close the issue

**Comment by samaxes** [comment]
Thanks! If you come by the same issue and believe it is related with this plugin, please fell free to reopen the issue so we can discuss it further.
