### ISSUE TITLE
Avoid warnings with Google Closure

### ISSUE THREAD

**Issue by JoseGoncalves** [samaxes/minify-maven-plugin#77]
HI,

When I minify a third-party library with the plugin configured to use Google Closure I get a lot of warnings like this:

> Oct 28, 2014 6:30:45 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: xxxxx.all.js:5914: WARNING - Parse error. illegal use of unknown JSDoc tag "category"; ignoring it
     * @category Utilities

Is there a way to configure the plugin to avoid these type of warnings?

I have found that this was solved upstream with a new option:

[Add an option to ignore unknown jsdoc tags](https://code.google.com/p/closure-compiler/issues/detail?id=901)

**Comment by OzoneGrif** [comment]
I have a similar issue, but it prevents Maven from continuing (CLOSURE compiler)
```
Sep 28, 2016 10:25:10 PM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: test.min.js:6634: ERROR - Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting newer versions of JS, set the appropriate language_in option.
			        'Accept': 'application/json',
			                                    ^

Sep 28, 2016 10:25:10 PM com.google.javascript.jscomp.LoggerErrorManager printSummary
WARNING: 25 error(s), 0 warning(s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by samaxes** [comment]
PR #74 should allow to avoid these warnings.
If not, please feel free to reopen this issue.
