### ISSUE TITLE
Closure Dependency Sorting Doesn't Work

### ISSUE THREAD

**Issue by buggtb** [samaxes/minify-maven-plugin#80]
I'm new to all this closure stuff, but from what I can tell the dependency sorting doesn't work(for me at least)

a) because its missing                     options.setManageClosureDependencies(true); (maybe)
b) because its trying to sort on an already merged file.

Tom

**Comment by samaxes** [comment]
Hi @buggtb, I will take a look at this in the next milestone.

**Comment by nsaintaubert** [comment]
Does closure dependency works on 1.7.4? or do we shall wait for 1.7.6.
I cant make it work on 1.7.4, please just give a feedback to know if it come from out configuration or if we just have to wait for the feature.
Great plugin.
Best Regards

**Comment by samaxes** [comment]
Hi @nsaintaubert, it has never been supported.
Unfortunately, you will have to wait a bit until I find the time to add it to the plugin.

**Comment by nsaintaubert** [comment]
Ok, thanks for attending.
