### ISSUE TITLE
Support closure extra_annotation_name parameter

### ISSUE THREAD

**Issue by dcendents** [samaxes/minify-maven-plugin#83]
Hi,

We are using ngdoc which is an extension of jsDoc for angularjs.
During the minification by google closure, there are a lot of warnings like this: "WARNING - Parse error. illegal use of unknown JSDoc tag "ngdoc"; ignoring it"

This can be turned off by using the command line switch --extra_annotation_name ngdoc --extra_annotation_name anyOtherAnn etc.

Can you please add a new configuration parameter so we can configure extra parameters to be sent to the compressor engine?

Thanks

**Comment by jcjolley** [comment]
Has there been any progress on this?  Using angular spawns a wall of parse error warnings.

**Comment by samaxes** [comment]
PR #117 merged into master.
