### ISSUE TITLE
how to change html script tag pointing to the minified file??

### ISSUE THREAD

**Issue by azerafati** [samaxes/minify-maven-plugin#89]
I'm trying to figure out how to use your plugin, and it works very well just as I wanted ,
my problem must be my own lack of info on maven, but I can't find how should I manage to change my html pages to point to the minified script, 

		<script src="/resources/js/1.js"></script>
		<script src="/resources/js/2.js"></script>

after the compression

		<script src="/resources/js/all.min.js"></script>

in case I need some other tools or documents on this, I guess it would be perfect to mention them on documentations too, thanks

**Comment by jieryn** [comment]
Just update your html pages as you gave in your second example. Your development environment should detect when you make changes to 1.js and then automatically invoke minify maven plugin. That way your all.min.js is always up to date, and your html page refers to all.min.js

Please close this issue, thanks!
