### ISSUE TITLE
Error in minify should break the build

### ISSUE THREAD

**Issue by githubdoramon** [samaxes/minify-maven-plugin#91]
When the plugin find an error and don´t create the final js file, the maven build should not be completed as it hasn't found any issue. Is there any way to accomplish this?

**Comment by khmarbaise** [comment]
Is there an option available to break the build if for example the java script compilation fails ?

**Comment by mjcannon** [comment]
+1

**Comment by githubdoramon** [comment]
just had my site broken for a whole day because of this :(

**Comment by samaxes** [comment]
Should be working on the next 1.7.5 version.
