### ISSUE TITLE
Delete old files after merge

### ISSUE THREAD

**Issue by NelsonRosenberg** [samaxes/minify-maven-plugin#95]
Could we get an option to delete the old .css files after they have been merge and the final source created?

Thanks a lot.

**Comment by stgunholy** [comment]
This would be really nice feature indeed.

**Comment by sadiqodho** [comment]
Please tell me how to delete old file. and new created file name should be script.js not script-min.js

**Comment by samaxes** [comment]
You can exclude old source files from the WAR package: http://samaxes.github.io/minify-maven-plugin/examples/exclude.html.
